import { normalizeText } from "@/lib/utils";

export type SchoolOption = {
  id: string;
  label: string;
  normalizedName: string;
  aliases?: string[];
};

const SCHOOL_NAMES = [
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Brown University",
  "University of Pennsylvania",
  "Massachusetts Institute of Technology",
  "Stanford University",
  "California Institute of Technology",
  "University of California Berkeley",
  "University of California Los Angeles",
  "University of California San Diego",
  "University of Southern California",
  "San Diego State University",
  "California State University Long Beach",
  "University of Washington",
  "Seattle University",
  "University of Oregon",
  "Portland State University",
  "Boise State University",
  "University of Idaho",
  "Arizona State University",
  "University of Arizona",
  "University of Colorado Boulder",
  "University of Utah",
  "University of Nevada Las Vegas",
  "University of New Mexico",
  "University of Texas at Austin",
  "Texas A&M University",
  "University of Houston",
  "Rice University",
  "Baylor University",
  "Southern Methodist University",
  "Louisiana State University",
  "Tulane University",
  "University of Oklahoma",
  "University of Kansas",
  "University of Missouri",
  "University of Nebraska-Lincoln",
  "University of Iowa",
  "Iowa State University",
  "University of Minnesota",
  "University of Wisconsin-Madison",
  "University of Illinois Urbana-Champaign",
  "Northwestern University",
  "DePaul University",
  "Loyola University Chicago",
  "University of Chicago",
  "University of Michigan",
  "Michigan State University",
  "Wayne State University",
  "Ohio State University",
  "Case Western Reserve University",
  "University of Cincinnati",
  "Cleveland State University",
  "University of Notre Dame",
  "Purdue University",
  "Indiana University Bloomington",
  "University of Kentucky",
  "University of Louisville",
  "Vanderbilt University",
  "University of Tennessee",
  "University of Alabama",
  "Auburn University",
  "Georgia Institute of Technology",
  "University of Georgia",
  "Emory University",
  "Georgia State University",
  "University of Florida",
  "Florida State University",
  "University of Central Florida",
  "Florida International University",
  "University of Miami",
  "University of North Carolina at Chapel Hill",
  "North Carolina State University",
  "Duke University",
  "Wake Forest University",
  "University of South Carolina",
  "Clemson University",
  "Virginia Tech",
  "University of Virginia",
  "George Mason University",
  "George Washington University",
  "Georgetown University",
  "University of Maryland",
  "Johns Hopkins University",
  "Towson University",
  "Temple University",
  "Drexel University",
  "Pennsylvania State University",
  "Carnegie Mellon University",
  "University of Pittsburgh",
  "Rutgers University",
  "Princeton Theological Seminary",
  "New York University",
  "Fordham University",
  "Syracuse University",
  "University at Buffalo",
  "Rochester Institute of Technology",
  "Boston University",
  "Northeastern University",
  "Tufts University",
  "Emerson College",
  "Suffolk University",
  "Boston College",
  "University of Massachusetts Amherst",
  "Brandeis University",
  "Worcester Polytechnic Institute",
  "University of Vermont",
  "Dartmouth College",
  "University of New Hampshire",
  "University of Rhode Island",
  "Brown University",
  "University of Connecticut",
  "McGill University",
  "University of Toronto",
  "University of British Columbia",
  "University of Waterloo",
  "University of Alberta",
  "Imperial College London",
  "University of Oxford",
  "University of Cambridge",
  "King's College London",
  "University of Manchester",
  "University College London",
  "Trinity College Dublin",
  "University College Dublin",
  "Technical University of Munich",
  "University of Amsterdam",
  "Sorbonne University",
  "National University of Singapore",
  "Nanyang Technological University",
  "University of Melbourne",
  "University of Sydney",
  "Monash University",
  "Open University",
  "Community College",
  "Trade School",
  "Technical School",
  "Vocational School",
  "High School",
  "Bunker Hill Community College",
  "Northern Virginia Community College",
  "Houston Community College",
  "CUNY LaGuardia Community College",
  "Santa Monica College",
  "Austin Community College",
  "Miami Dade College",
  "Broward College",
  "Cerritos College",
  "Dallas College",
  "Pima Community College",
  "Tidewater Community College"
];

const SCHOOLS: SchoolOption[] = SCHOOL_NAMES.map((label) => ({
  id: normalizeText(label).replace(/\s+/g, "-"),
  label,
  normalizedName: normalizeText(label)
}));

export function searchSchools(query: string) {
  const normalizedQuery = normalizeText(query);
  return SCHOOLS.filter((school) => {
    if (!normalizedQuery) return true;
    return normalizeText([school.label, school.normalizedName, ...(school.aliases ?? [])].join(" ")).includes(normalizedQuery);
  });
}
