import { normalizeText } from "@/lib/utils";

export type SkillOption = {
  id: string;
  label: string;
};

const SKILLS = [
  "Accounting",
  "Accounts Payable",
  "Accounts Receivable",
  "Administrative Support",
  "Adobe Creative Suite",
  "Agile",
  "Analytical Thinking",
  "Appointment Scheduling",
  "AutoCAD",
  "B2B Sales",
  "Budgeting",
  "Business Analysis",
  "Calendar Management",
  "Cash Handling",
  "Change Management",
  "Childcare",
  "Classroom Management",
  "Client Relations",
  "Clinical Documentation",
  "Communication",
  "Compliance",
  "Conflict Resolution",
  "Construction Safety",
  "Content Writing",
  "Contract Negotiation",
  "Cooking",
  "Copywriting",
  "CRM",
  "Critical Thinking",
  "Customer Service",
  "Data Analysis",
  "Data Entry",
  "Dental Assisting",
  "Digital Marketing",
  "Documentation",
  "Editing",
  "Electrical Troubleshooting",
  "Electronic Health Records",
  "Employee Training",
  "Event Planning",
  "Excel",
  "Facebook Ads",
  "Filing",
  "Financial Analysis",
  "Forklift Operation",
  "Front Desk Operations",
  "Fundraising",
  "Graphic Design",
  "Google Ads",
  "Google Analytics",
  "Google Workspace",
  "Healthcare Administration",
  "HIPAA",
  "Hiring",
  "Hospitality",
  "HRIS",
  "Inventory Management",
  "Invoicing",
  "Java",
  "JavaScript",
  "Jira",
  "KPI Reporting",
  "Leadership",
  "Lesson Planning",
  "Light Bookkeeping",
  "Logistics",
  "Maintenance",
  "Market Research",
  "Mechanical Repair",
  "Medical Billing",
  "Medical Coding",
  "Merchandising",
  "Microsoft Office",
  "Negotiation",
  "Networking",
  "Nursing",
  "Occupational Safety",
  "Onboarding",
  "Patient Care",
  "Payroll",
  "Photography",
  "Plumbing",
  "PowerPoint",
  "Presentation Skills",
  "Process Improvement",
  "Procurement",
  "Project Coordination",
  "Project Management",
  "Property Management",
  "Public Speaking",
  "Python",
  "Quality Assurance",
  "QuickBooks",
  "Reception",
  "Recruiting",
  "Report Writing",
  "Research",
  "Retail Sales",
  "Risk Management",
  "Salesforce",
  "Scheduling",
  "Social Media",
  "Software Testing",
  "Spreadsheet Management",
  "SQL",
  "Stakeholder Management",
  "Strategic Planning",
  "Supervision",
  "Supply Chain",
  "Teaching",
  "Team Building",
  "Team Leadership",
  "Technical Support",
  "Time Management",
  "Training",
  "Troubleshooting",
  "UX Design",
  "Vendor Management",
  "Warehouse Operations",
  "Word",
  "WordPress",
  "Writing"
];

export const SKILL_OPTIONS: SkillOption[] = SKILLS.map((label) => ({
  id: normalizeText(label).replace(/\s+/g, "-"),
  label
}));

export function searchSkills(query: string) {
  const normalizedQuery = normalizeText(query);
  return SKILL_OPTIONS.filter((option) => {
    if (!normalizedQuery) return true;
    return normalizeText(option.label).includes(normalizedQuery);
  }).slice(0, 10);
}
